backend/build.gradle
backend/src/main/java/com/multi/mariage/global/exception/exception/ErrorCode.java
backend/src/main/java/com/multi/mariage/global/exception/exception/MariageException.java

#11 
- `lombok` 주입
- `ErrorCode` 인터페이스 생성
- `MariageException` 생성

[BE] Custom Exception 구현

---

backend/.gitignore
backend/src/main/resources/security/application-database.yml
backend/src/main/resources/security/application-openWeatherMap.yml

[BE] .gitignore 수정

---

backend/src/main/java/com/multi/mariage/global/redis/RedisConfig.java
backend/src/main/java/com/multi/mariage/global/security/SecurityConfig.java
backend/src/main/java/com/multi/mariage/member/controller/MemberController.java
backend/src/main/java/com/multi/mariage/member/domain/Member.java
backend/src/main/java/com/multi/mariage/member/domain/MemberRepository.java
backend/src/main/java/com/multi/mariage/member/domain/embedded/Email.java
backend/src/main/java/com/multi/mariage/member/domain/embedded/Name.java
backend/src/main/java/com/multi/mariage/member/domain/embedded/Nickname.java
backend/src/main/java/com/multi/mariage/member/domain/embedded/Password.java
backend/src/main/java/com/multi/mariage/member/dto/request/MemberSignupRequest.java
backend/src/main/java/com/multi/mariage/member/exception/MemberErrorCode.java
backend/src/main/java/com/multi/mariage/member/exception/MemberException.java
backend/src/main/java/com/multi/mariage/member/service/MemberService.java
backend/src/main/resources/security/README.md
frontend/src/components/Button/Like/Like.tsx

[BE] 회원가입 기능 

---

frontend/jest.config.js
frontend/package-lock.json
frontend/package.json
frontend/src/constants/rule.ts
frontend/src/pages/SignUp/SignUp.styled.ts
frontend/src/pages/SignUp/SignUp.tsx
frontend/src/pages/SignUp/Signup.test.ts
frontend/src/pages/SignUp/Validate.ts

#46 
- 각 항목에 대한 검증 기능 구현
- 테스트 코드 작성
- jest 라이브러리

[FE] 회원가입 검증 기능 구현

---

backend/src/main/java/com/multi/mariage/global/exception/ControllerAdvice.java
backend/src/main/java/com/multi/mariage/global/exception/dto/response/ExceptionResponse.java
backend/src/main/java/com/multi/mariage/global/exception/exception/GlobalErrorCode.java
backend/src/main/java/com/multi/mariage/member/controller/MemberController.java
backend/src/main/java/com/multi/mariage/member/domain/embedded/Email.java
backend/src/test/java/com/multi/mariage/member/domain/embedded/EmailTest.java
frontend/src/constants/path.ts
frontend/src/pages/NotFound/NotFound.styled.ts
frontend/src/pages/NotFound/NotFound.tsx
frontend/src/pages/SignUp/SignUp.styled.ts
frontend/src/pages/SignUp/SignUp.tsx

[BE] Controller Advice 구현

---

frontend/src/App.tsx
frontend/src/apis/request/auth.ts
frontend/src/components/Animation/Soju.tsx
frontend/src/components/Animation/Wine.tsx
frontend/src/components/Error/Error.tsx
frontend/src/components/Loading/Loading.tsx
frontend/src/components/RangeMultiSlider_F/RangeMultiSlider_F.styled.ts
frontend/src/components/RangeMultiSlider_F/RangeMultiSlider_F.tsx
frontend/src/components/RangeMultiSlider_M/RangeMultiSlider_M.styled.ts
frontend/src/components/RangeMultiSlider_M/RangeMultiSlider_M.tsx
frontend/src/constants/message.ts
frontend/src/pages/Main/Main.tsx
frontend/src/pages/NotFound/NotFound.tsx
frontend/src/pages/Pages.ts
frontend/src/pages/SignUp/SignUp.tsx
frontend/src/routes/Routes.tsx
frontend/tsconfig.json
frontend/webpack.config.js

[FE] 경로 별칭 설정

---

frontend/src/pages/Main/Main.styled.ts
frontend/src/pages/Main/Main.tsx
frontend/src/pages/Main/Visual/Visual.styled.ts
frontend/src/pages/Main/Visual/Visual.tsx

#41 
- 메인페이지 비주얼영역 fade캐러셀 구현
- 메인페이지 임시레이아웃 추가

[FE] 메인페이지 비주얼영역 구현

---

backend/src/main/java/com/multi/mariage/auth/controller/AuthController.java
backend/src/main/java/com/multi/mariage/auth/domain/AuthRepository.java
backend/src/main/java/com/multi/mariage/auth/domain/RefreshToken.java
backend/src/main/java/com/multi/mariage/auth/dto/request/LoginRequest.java
backend/src/main/java/com/multi/mariage/auth/dto/response/TokenResponse.java
backend/src/main/java/com/multi/mariage/auth/exception/AuthErrorCode.java
backend/src/main/java/com/multi/mariage/auth/exception/AuthException.java
backend/src/main/java/com/multi/mariage/auth/service/AuthService.java
backend/src/main/java/com/multi/mariage/auth/service/CustomUserDetailService.java
backend/src/main/java/com/multi/mariage/auth/support/JwtAccessDeniedHandler.java
backend/src/main/java/com/multi/mariage/auth/support/JwtAuthenticationEntryPoint.java
backend/src/main/java/com/multi/mariage/auth/support/JwtFilter.java
backend/src/main/java/com/multi/mariage/auth/support/JwtSecurityConfig.java
backend/src/main/java/com/multi/mariage/auth/support/TokenProvider.java
backend/src/main/java/com/multi/mariage/global/security/SecurityConfig.java
backend/src/main/java/com/multi/mariage/global/security/SecurityUtil.java
backend/src/main/java/com/multi/mariage/member/controller/MemberController.java
backend/src/main/java/com/multi/mariage/member/domain/Member.java
backend/src/main/java/com/multi/mariage/member/domain/MemberRepository.java
backend/src/main/java/com/multi/mariage/member/domain/Role.java
backend/src/main/java/com/multi/mariage/member/domain/embedded/Password.java
backend/src/main/java/com/multi/mariage/storage/controller/StorageController.java
backend/src/test/java/com/multi/mariage/common/annotation/ControllerTest.java
backend/src/test/java/com/multi/mariage/common/fixture/MemberFixture.java
backend/src/test/java/com/multi/mariage/storage/controller/StorageControllerTest.java

#27 
- JWT 설정
- Security 설정
- 로그인 기능 구현

[BE] 로그인 기능 구현

---

backend/src/main/java/com/multi/mariage/auth/annotation/Authenticated.java
backend/src/main/java/com/multi/mariage/auth/annotation/AuthenticatedArgumentResolver.java
backend/src/main/java/com/multi/mariage/auth/controller/AuthController.java
backend/src/main/java/com/multi/mariage/auth/domain/RefreshToken.java
backend/src/main/java/com/multi/mariage/auth/dto/AuthMember.java
backend/src/main/java/com/multi/mariage/auth/dto/request/ReissueRequest.java
backend/src/main/java/com/multi/mariage/auth/service/AuthService.java
backend/src/main/java/com/multi/mariage/auth/support/TokenProvider.java
backend/src/main/java/com/multi/mariage/global/config/WebConfig.java
backend/src/test/java/com/multi/mariage/common/annotation/ControllerTest.java

[FE] 로그아웃 기능 구현

---

backend/src/main/java/com/multi/mariage/auth/dto/request/LoginRequest.java
backend/src/main/java/com/multi/mariage/member/controller/MemberController.java
backend/src/main/java/com/multi/mariage/member/service/MemberService.java
backend/src/test/java/com/multi/mariage/auth/service/AuthServiceTest.java
backend/src/test/java/com/multi/mariage/common/fixture/MemberFixture.java
backend/src/test/java/com/multi/mariage/member/controller/MemberControllerTest.java
backend/src/test/java/com/multi/mariage/member/service/MemberServiceTest.java
backend/src/test/java/com/multi/mariage/storage/controller/StorageControllerTest.java
backend/src/test/java/com/multi/mariage/storage/repository/StorageRepositoryTest.java
backend/src/test/java/com/multi/mariage/storage/service/StorageServiceTest.java
backend/src/test/java/com/multi/mariage/weather/service/WeatherServiceTest.java

[BE] 탈퇴 및 로그아웃 기능 구현

---

backend/src/main/java/com/multi/mariage/auth/annotation/AuthenticatedArgumentResolver.java
backend/src/main/java/com/multi/mariage/auth/dto/request/ReissueRequest.java
backend/src/main/java/com/multi/mariage/auth/service/AuthService.java
backend/src/main/java/com/multi/mariage/auth/support/TokenProvider.java
backend/src/test/java/com/multi/mariage/auth/controller/AuthControllerTest.java
backend/src/test/java/com/multi/mariage/auth/service/AuthServiceTest.java
backend/src/test/java/com/multi/mariage/common/annotation/ControllerTest.java
backend/src/test/java/com/multi/mariage/member/controller/MemberControllerTest.java
backend/src/test/java/com/multi/mariage/storage/controller/StorageControllerTest.java

[BE] 인증 처리 컨트롤러 테스트 코드 작성

---

frontend/src/App.tsx
frontend/src/apis/request/auth.ts
frontend/src/apis/request/member.ts
frontend/src/constants/path.ts
frontend/src/hooks/useAuth.ts
frontend/src/pages/Login/Login.styled.ts
frontend/src/pages/Login/Login.tsx
frontend/src/pages/SignUp/SignUp.styled.ts
frontend/src/pages/SignUp/SignUp.tsx
frontend/src/store/status.ts
frontend/src/types/user.ts
frontend/src/utils/auth.ts
frontend/src/utils/token.ts

[FE] 로그인 페이지 UI와 기능을 구현

---

backend/src/main/java/com/multi/mariage/category/domain/UpperCategory.java
backend/src/main/java/com/multi/mariage/member/controller/MemberController.java
backend/src/main/java/com/multi/mariage/member/domain/Member.java
backend/src/main/java/com/multi/mariage/member/dto/request/UpdateNicknameRequest.java
backend/src/main/java/com/multi/mariage/member/dto/request/UpdatePasswordRequest.java
backend/src/main/java/com/multi/mariage/member/dto/response/MyInfoResponse.java
backend/src/main/java/com/multi/mariage/member/dto/response/UpdateImageResponse.java
backend/src/main/java/com/multi/mariage/member/dto/response/UpdateNicknameResponse.java
backend/src/main/java/com/multi/mariage/member/exception/MemberErrorCode.java
backend/src/main/java/com/multi/mariage/member/service/MemberService.java
backend/src/main/java/com/multi/mariage/storage/controller/StorageController.java
backend/src/main/java/com/multi/mariage/storage/exception/StorageErrorCode.java
backend/src/main/java/com/multi/mariage/storage/service/StorageService.java
backend/src/test/java/com/multi/mariage/member/controller/MemberControllerTest.java
backend/src/test/java/com/multi/mariage/member/service/MemberServiceTest.java
backend/src/test/java/com/multi/mariage/storage/service/StorageServiceTest.java

[FE] 마이페이지에서 프로필 사진 수정 기능 구현

---

backend/src/main/java/com/multi/mariage/member/controller/MemberController.java
backend/src/main/java/com/multi/mariage/member/dto/response/MyInfoResponse.java
backend/src/main/java/com/multi/mariage/member/service/MemberService.java
backend/src/main/java/com/multi/mariage/storage/service/StorageService.java
backend/src/test/java/com/multi/mariage/member/controller/MemberControllerTest.java
backend/src/test/java/com/multi/mariage/member/service/MemberServiceTest.java

[BE] 나의 프로필 정보 조회 기능을 구현

---

frontend/src/components/RangeMultiSlider_M/RangeMultiSlider_M.styled.ts
frontend/src/pages/Main/Recommend/ProductCard/ProductCard.tsx
frontend/src/pages/Main/SearchFilter/SearchFilter.styled.ts
frontend/src/pages/Main/SearchFilter/SelectBox/SelectBox.styled.ts
frontend/src/pages/Main/SearchFilter/SelectBox/SelectBox.tsx

#88 
- 해상도 1920px ~ : 분류 필터 세로 정렬로 수정 : find버튼 위치 수정
- 테두리 컬러 및 효과 수정
- 카드 컴포넌트 국기이미지 데이터이름 수정

[FE] 메인페이지 검색필터 UI 수정

---

frontend/src/App.tsx
frontend/src/apis/request/category.ts
frontend/src/components/Header/Header.tsx
frontend/src/components/RangeMultiSlider_M/RangeMultiSlider_M.styled.ts
frontend/src/components/RangeMultiSlider_M/RangeMultiSlider_M_ABV.tsx
frontend/src/components/RangeMultiSlider_M/RangeMultiSlider_M_Star.tsx
frontend/src/constants/key.ts
frontend/src/hooks/useCategory.ts
frontend/src/pages/Main/SearchFilter/SearchFilter.tsx
frontend/src/pages/Main/SearchFilter/SelectBox/SelectBox.styled.ts
frontend/src/store/status.ts

[FE] 카테고리 저장기능 React-Query 적용

---

backend/src/main/java/com/multi/mariage/global/config/WebConfig.java
backend/src/main/java/com/multi/mariage/global/security/SecurityConfig.java
backend/src/main/java/com/multi/mariage/storage/controller/StorageController.java
backend/src/main/java/com/multi/mariage/storage/service/StorageService.java
backend/src/main/resources/application-logging.yml
backend/src/test/java/com/multi/mariage/member/service/MemberServiceTest.java
backend/src/test/java/com/multi/mariage/storage/controller/StorageControllerTest.java
backend/src/test/java/com/multi/mariage/storage/service/StorageServiceTest.java

[BE] 이미지 출력 기능 구현

---

backend/src/main/java/com/multi/mariage/member/controller/MemberController.java
backend/src/main/java/com/multi/mariage/member/dto/response/NicknameResponse.java
backend/src/main/java/com/multi/mariage/member/service/MemberService.java
backend/src/test/java/com/multi/mariage/member/controller/MemberControllerTest.java
backend/src/test/java/com/multi/mariage/member/service/MemberServiceTest.java
frontend/src/apis/request/member.ts
frontend/src/components/Header/Header.tsx
frontend/src/components/Header/User/Profile.styled.ts
frontend/src/components/Header/User/Profile.tsx
frontend/src/constants/path.ts
frontend/src/hooks/useNickname.ts
frontend/src/store/status.ts

#101 
- 별칭 출력 기능 구현
- 별칭 테스트 코드 작성
- recoil에 회원의 별칭 저장

[FE] 헤더에서 회원 별칭을 조회하는 기능 구현

---

backend/src/main/java/com/multi/mariage/category/controller/CategoryController.java
backend/src/main/java/com/multi/mariage/category/dto/response/DrinkLowerCategoryResponse.java
backend/src/main/java/com/multi/mariage/category/dto/response/DrinkUpperCategoryResponse.java
backend/src/main/java/com/multi/mariage/category/service/DrinkLowerCategoryService.java
backend/src/main/java/com/multi/mariage/category/service/DrinkUpperCategoryService.java
backend/src/main/java/com/multi/mariage/category/vo/drinkLower/DrinkLowerCategoriesVO.java
backend/src/main/java/com/multi/mariage/category/vo/drinkLower/DrinkLowerCategoryValuesVO.java
backend/src/main/java/com/multi/mariage/category/vo/drinkLower/DrinkLowerSubCategoriesVO.java
backend/src/main/java/com/multi/mariage/category/vo/drinkUpper/DrinkUpperCategoriesVO.java
backend/src/main/java/com/multi/mariage/category/vo/drinkUpper/DrinkUpperCategoryValuesVO.java
backend/src/test/java/com/multi/mariage/category/service/DrinkLowerCategoryServiceTest.java
backend/src/test/java/com/multi/mariage/category/service/DrinkUpperCategoryServiceTest.java

[BE] 주류 카테고리 코드 리팩토링

---

backend/.gitignore
backend/build.gradle
backend/src/docs/asciidoc/Auth.adoc
backend/src/docs/asciidoc/Storage.adoc
frontend/src/hooks/useCategory.ts

[BE] Spring Rest Docs HTML 파일로 생성

---

backend/.gitignore
backend/src/docs/asciidoc/Category.adoc
backend/src/docs/asciidoc/Member.adoc

[BE]Rest docs html 문서 추가

---

backend/src/main/java/com/multi/mariage/category/vo/drink_lower/DrinkLowerCategoriesVO.java
backend/src/main/java/com/multi/mariage/category/vo/drink_lower/DrinkLowerCategoryValuesVO.java
backend/src/main/java/com/multi/mariage/category/vo/drink_lower/DrinkLowerSubCategoriesVO.java
backend/src/main/java/com/multi/mariage/category/vo/drink_upper/DrinkUpperCategoriesVO.java
backend/src/main/java/com/multi/mariage/category/vo/drink_upper/DrinkUpperCategoryValuesVO.java
backend/src/main/java/com/multi/mariage/category/vo/food/FoodCategoriesVO.java
backend/src/main/java/com/multi/mariage/product/controller/ProductController.java
backend/src/main/java/com/multi/mariage/product/dto/request/ProductSaveRequest.java
backend/src/main/java/com/multi/mariage/product/service/ProductService.java
backend/src/test/java/com/multi/mariage/category/controller/CategoryControllerTest.java
backend/src/test/java/com/multi/mariage/category/service/DrinkLowerCategoryServiceTest.java
backend/src/test/java/com/multi/mariage/category/service/DrinkUpperCategoryServiceTest.java
backend/src/test/java/com/multi/mariage/weather/service/WeatherServiceTest.java
frontend/src/apis/request/category.ts
frontend/src/constants/path.ts
frontend/src/pages/Admin/Admin.tsx
frontend/src/pages/Main/SearchFilter/SelectBox/SelectBox.tsx
frontend/src/types/category.ts

#115 
FoodCategory 반환값 수정한 내용입니다.
```json
{
"category" : [ {
"id" : 1,
"name" : "해산물",
"value" : "SEAFOOD"
}, {
"id" : 2,
"name" : "고기/구이",
"value" : "ROAST"
},
}
```
DrinkUpperCategrot API 반환값 수정한 내용입니다.
```json
{
"category" : [ {
"region" : "국내",
"value" : "LOCAL",
"categories" : [ {
"name" : "소주",
"value" : "LOCAL_SOJU"
},
}
```
DrinkLowerCategory API 반환값 수정한 내용입니다.
```json
{
"category" : [ {
"region" : "국내",
"regionValue" : "LOCAL",
"categories" : [ {
"name" : "LOCAL_SOJU",
"value" : "소주",
"subCategories" : [ {
"name" : "NORMAL_SOJU",
"value" : "희석식 소주"
}, {
"name" : "LUXURIOUS_SOJU",
"value" : "증류식 소주"
}, {
"name" : "FRUIT_SOJU",
"value" : "과일 소주"
} ]
},
}
```

[BE] Category API 반환값을 수정

---

frontend/src/components/Header/Dropdown/Dropdown.styled.ts
frontend/src/components/Header/Search/Search.styled.ts
frontend/src/components/Header/Search/Search.tsx
frontend/src/components/Header/User/Profile.styled.ts
frontend/src/layout/Layout.styled.ts
frontend/src/pages/Login/Login.styled.ts
frontend/src/pages/Login/Login.tsx
frontend/src/pages/Main/Main.styled.ts
frontend/src/pages/SignUp/SignUp.styled.ts
package-lock.json

[FE] 회원가입,로그인, header 수정

---

backend/src/main/java/com/multi/mariage/country/vo/CountriesVO.java
backend/src/main/java/com/multi/mariage/storage/service/StorageService.java
frontend/src/apis/request/category.ts
frontend/src/apis/request/product.ts
frontend/src/apis/request/storage.ts
frontend/src/constants/path.ts
frontend/src/hooks/useImage.ts
frontend/src/hooks/useSelect.ts
frontend/src/pages/Admin/Admin.styled.ts
frontend/src/pages/Admin/Admin.tsx
frontend/src/types/category.ts
frontend/src/types/id.ts
frontend/src/types/product.ts

[FE] 제품 등록 기능 구현

---

backend/src/docs/asciidoc/Auth.adoc
backend/src/docs/asciidoc/Category.adoc
backend/src/docs/asciidoc/Member.adoc
backend/src/docs/asciidoc/Storage.adoc

[BE] API Docs 수정

---

backend/src/main/java/com/multi/mariage/product/controller/ProductController.java
backend/src/main/java/com/multi/mariage/product/dto/request/ProductSaveRequest.java
backend/src/main/java/com/multi/mariage/product/dto/response/ProductFindResponse.java
backend/src/main/java/com/multi/mariage/product/service/ProductService.java
backend/src/main/java/com/multi/mariage/product/vo/ProductsVO.java
backend/src/main/java/com/multi/mariage/storage/exception/StorageErrorCode.java
backend/src/main/java/com/multi/mariage/storage/service/ImageService.java
backend/src/test/java/com/multi/mariage/common/fixture/ProductFixture.java
backend/src/test/java/com/multi/mariage/product/service/ProductServiceTest.java

[BE] 제품 조회, 등록 기능 구현

---

frontend/src/apis/axios.ts
frontend/src/apis/request/member.ts
frontend/src/components/Header/Search/Search.tsx
frontend/src/constants/path.ts
frontend/src/hooks/useInput.ts
frontend/src/pages/Admin/Admin.tsx
frontend/src/pages/MyInformation/Profile/Profile.styled.ts
frontend/src/pages/MyInformation/Profile/Profile.tsx
package-lock.json

[FE] 마이프로필 정보 조회와 사진 별칭 수정 기능 구현

---

backend/src/main/java/com/multi/mariage/product/controller/ProductController.java
frontend/src/apis/request/product.ts
frontend/src/pages/Admin/Admin.tsx

[FE] 어드민 페이지에서 주류 등록 기능 구현

---

frontend/src/components/Header/Dropdown/Dropdown.tsx
frontend/src/components/Header/Header.tsx
frontend/src/types/category.ts

[FE] 헤더에서 카테고리의 데이터 값이 출력되는 현상 수정

---

frontend/src/pages/MyInformation/Profile/Profile.tsx
frontend/src/pages/SignUp/SignUp.tsx

[FE] 회원가입, 로그인 페이지의 링크 history 문제 해결

---

backend/src/main/java/com/multi/mariage/auth/annotation/AuthenticatedArgumentResolver.java
backend/src/main/java/com/multi/mariage/auth/exception/AuthErrorCode.java
backend/src/main/java/com/multi/mariage/auth/support/JwtAccessDeniedHandler.java
backend/src/main/java/com/multi/mariage/auth/support/JwtAuthenticationEntryPoint.java
backend/src/main/java/com/multi/mariage/auth/support/JwtFilter.java
backend/src/main/java/com/multi/mariage/auth/support/JwtSecurityConfig.java
backend/src/main/java/com/multi/mariage/global/exception/ControllerAdvice.java
backend/src/main/java/com/multi/mariage/global/exception/exception/GlobalErrorCode.java
backend/src/main/java/com/multi/mariage/global/security/SecurityConfig.java
frontend/src/apis/axios.ts
frontend/src/apis/request/auth.ts
frontend/src/components/Header/User/Profile.tsx
frontend/src/constants/path.ts
frontend/src/hooks/useAuth.ts
frontend/src/hooks/useNickname.ts
frontend/src/pages/Login/Login.tsx
frontend/src/types/token.ts

[BE, FE] 엑세스 토큰을 재발급 하는 기능을 구현

---

backend/src/main/java/com/multi/mariage/global/data/Fixture/ProductFixture.java
backend/src/main/java/com/multi/mariage/global/data/LoaderData.java
backend/src/main/java/com/multi/mariage/product/domain/ProductRepository.java
backend/src/main/java/com/multi/mariage/product/domain/query/ProductRepositoryCustom.java
backend/src/main/java/com/multi/mariage/product/domain/query/ProductRepositoryImpl.java
backend/src/test/java/com/multi/mariage/common/fixture/ProductFixture.java
backend/src/test/java/com/multi/mariage/product/domain/ProductRepositoryQueryTest.java
backend/src/test/java/com/multi/mariage/product/service/ProductServiceTest.java

[BE] 제품 검색 기능을 구현과 테스트 코드 작성

---

frontend/src/components/StarRate/Common/StarRate.styled.ts
frontend/src/components/StarRate/Common/StarRate.tsx
frontend/src/pages/Detail/Detail.styled.ts
frontend/src/pages/Detail/Detail.tsx
frontend/src/pages/Detail/Pairing/Pairing.styled.ts
frontend/src/pages/Detail/Pairing/Pairing.tsx
frontend/src/pages/Detail/ProductContent/ProductContent.tsx
frontend/src/pages/Detail/Review/RateStatistic/RateStatistic.styled.ts
frontend/src/pages/Detail/Review/RateStatistic/RateStatistic.tsx
frontend/src/pages/Detail/Review/Review.styled.ts
frontend/src/pages/Detail/Review/Review.tsx
frontend/src/pages/Detail/Review/ReviewCategory/ReviewCategory.styled.ts
frontend/src/pages/Detail/Review/ReviewCategory/ReviewCategory.tsx
frontend/src/pages/Detail/Review/ReviewContent/ReviewContent.styled.ts
frontend/src/pages/Detail/Review/ReviewEdit/FoodContent/FoodCategory.styled.ts
frontend/src/pages/Detail/Review/ReviewEdit/FoodContent/FoodCategory.tsx
frontend/src/pages/Detail/Review/ReviewEdit/FoodContent/FoodImg.styled.ts
frontend/src/pages/Detail/Review/ReviewEdit/FoodContent/FoodImg.tsx
frontend/src/pages/Detail/Review/ReviewEdit/HashTag/HashTag.styled.ts
frontend/src/pages/Detail/Review/ReviewEdit/HashTag/HashTag.tsx
frontend/src/pages/Detail/Review/ReviewEdit/ReviewEdit.styled.ts
frontend/src/pages/Detail/Review/ReviewEdit/ReviewEdit.tsx
frontend/src/pages/Detail/Review/ReviewEditModal/ReviewEditModal.styled.ts
frontend/src/pages/Detail/Review/ReviewEditModal/ReviewEditModal.tsx

리뷰작성 모달 컴포넌트 구현
- 리뷰작성 모달 컴포넌트 전체 UI 구현
- 모달 내 슬라이드 기능 추가
- 술 별점, 궁합 별점 기능 추가
- 리뷰 작성폼 추가
- 음식 카테고리 선택 기능 및 UI 구현
- 선택된 카테고리 데이터 출력
- 음식 사진 업로드 및 프리뷰 기능, UI 구현
- 해시태그 기능 및 UI 구현
다른 컴포넌트 미디어 쿼리 등 UI 수정

[FE] 리뷰작성 모달 컴포넌트 구현 - #123

---

frontend/src/components/Bar/PercentageBar/PercentageBar.styled.ts
frontend/src/components/Bar/PercentageBar/PercentageBar.tsx

[FE] 리뷰 통계 컴포넌트 내부 바 스타일 수정

---

backend/src/main/java/com/multi/mariage/auth/controller/AuthController.java
backend/src/main/java/com/multi/mariage/auth/service/AuthService.java
backend/src/main/java/com/multi/mariage/auth/support/TokenProvider.java
frontend/src/components/Header/User/Profile.tsx

[FE] 엑세스 토큰 재발행 버그 수정

---

frontend/src/assets/svg/SVG.tsx
frontend/src/assets/svg/rating/rating000.svg
frontend/src/assets/svg/rating/rating012.svg
frontend/src/assets/svg/rating/rating034.svg
frontend/src/assets/svg/rating/rating055.svg
frontend/src/assets/svg/rating/rating067.svg
frontend/src/assets/svg/rating/rating089.svg
frontend/src/assets/svg/rating/rating100.svg
frontend/src/components/Detail/Review/ReviewContent/ReviewContent.tsx
frontend/src/components/Product/ProductCard/ProductCard.styled.ts
frontend/src/components/Product/ProductCard/ProductCard.tsx
frontend/src/components/Slider/RangeMultiSlider_F/RangeMultiSlider_F.tsx
frontend/src/components/StarRate/Average/SvgStarRateAverage.styled.ts
frontend/src/components/StarRate/Average/SvgStarRateAverage.tsx
frontend/src/pages/Product/Product.tsx

#125 
- SVG 이미지 파일 컴포넌트로 변환
- 별점이미지 출력 로직 구현
- 새로 만든 컴포넌트로 마이그레이션
새로운 별점 컴포넌트를 사용하였더니 별점의 위치기 이상해 지는  문제가 발생
해당 문제는 임시로 해결해 두었지만 추후 병합시 문제가 될 여지가 보입니다.

[FE] 별점평균 컴포넌트 활용시 데이터값이 적용 안되는 버그 수정

---

frontend/src/components/Header/User/Profile.tsx
frontend/src/components/MyInformation/Profile/Profile.tsx
frontend/src/hooks/useUserInfo.ts
frontend/src/pages/Login/Login.tsx

[FE] 회원의 별칭을 수정시 헤더에 반영이 안되는 현상이 발생 수정

---

frontend/src/components/Review/ReviewList.styled.ts
frontend/src/components/Review/ReviewList.tsx
frontend/src/constants/path.ts
frontend/src/pages/Pages.ts
frontend/src/pages/Review/Review.styled.ts
frontend/src/pages/Review/Review.tsx
frontend/src/routes/Routes.tsx

#175 
Review 페이지 구현
- 전체 UI 구현 (미디어쿼리)
- 리뷰 컴포넌트 구현 (미디어쿼리)

[FE] Review 페이지 구현

---

frontend/src/components/Detail/ProductContent/ProductContent.styled.ts
frontend/src/components/Detail/Review/ReviewContent/ReviewContent.styled.ts
frontend/src/components/Review/ReviewList.styled.ts
frontend/src/components/Review/ReviewList.tsx

#187 
- 별점 컴포넌트가 사용된 부분의 UI 수정

[FE] 별점 컴포넌트 UI 수정

---

backend/src/main/java/com/multi/mariage/global/data/LoaderData.java
backend/src/main/java/com/multi/mariage/global/exception/ControllerAdvice.java
backend/src/main/java/com/multi/mariage/hashtag/domain/Hashtag.java
backend/src/main/java/com/multi/mariage/hashtag/domain/HashtagRepository.java
backend/src/main/java/com/multi/mariage/hashtag/service/HashtagService.java
backend/src/main/java/com/multi/mariage/member/domain/Member.java
backend/src/main/java/com/multi/mariage/review/controller/ReviewModifyController.java
backend/src/main/java/com/multi/mariage/review/domain/Review.java
backend/src/main/java/com/multi/mariage/review/dto/request/ReviewSaveRequest.java
backend/src/main/java/com/multi/mariage/review/dto/resonse/ReviewSaveResponse.java
backend/src/main/java/com/multi/mariage/review/service/ReviewModifyService.java
backend/src/main/java/com/multi/mariage/review_hashtag/domain/ReviewHashTag.java
backend/src/main/java/com/multi/mariage/review_hashtag/domain/ReviewHashtag.java
backend/src/main/java/com/multi/mariage/review_hashtag/domain/ReviewHashtagRepository.java
backend/src/main/java/com/multi/mariage/review_hashtag/service/ReviewHashtagService.java
backend/src/main/java/com/multi/mariage/weather/domain/Query/WeatherRepositoryCustom.java
backend/src/main/java/com/multi/mariage/weather/domain/Query/WeatherRepositoryImpl.java
backend/src/main/java/com/multi/mariage/weather/domain/WeatherRepository.java
backend/src/main/java/com/multi/mariage/weather/exception/WeatherErrorCode.java
backend/src/main/java/com/multi/mariage/weather/service/WeatherService.java
backend/src/test/java/com/multi/mariage/common/annotation/RepositoryTest.java
backend/src/test/java/com/multi/mariage/common/fixture/ReviewFixture.java
backend/src/test/java/com/multi/mariage/review_hashtag/domain/ReviewHashtagRepositoryTest.java
backend/src/test/java/com/multi/mariage/storage/repository/StorageRepositoryTest.java
backend/src/test/java/com/multi/mariage/weather/service/WeatherServiceTest.java
frontend/src/@types/review.ts
frontend/src/layout/Layout.styled.ts
frontend/src/store/status.ts

#183 
리뷰 기능을 구현하였습니다.
- 날씨 데이터에 따른 조회 방식 구현
- hashtag 테이블 재구성
- 저장 로직 구현

[BE] 리뷰 등록 기능을 구현

---

backend/src/docs/asciidoc/Auth.adoc
backend/src/docs/asciidoc/Category.adoc
backend/src/docs/asciidoc/Member.adoc
backend/src/docs/asciidoc/Review.adoc
backend/src/docs/asciidoc/Storage.adoc
backend/src/main/java/com/multi/mariage/product/controller/ProductModifyController.java
backend/src/main/java/com/multi/mariage/review/controller/ReviewModifyController.java
backend/src/main/java/com/multi/mariage/review_hashtag/domain/ReviewHashtag.java
backend/src/main/java/com/multi/mariage/weather/domain/Weather.java
backend/src/test/java/com/multi/mariage/common/annotation/ControllerTest.java
backend/src/test/java/com/multi/mariage/common/annotation/RepositoryTest.java
backend/src/test/java/com/multi/mariage/common/annotation/ServiceTest.java
backend/src/test/java/com/multi/mariage/common/fixture/HashtagFixture.java
backend/src/test/java/com/multi/mariage/common/fixture/ImageFixture.java
backend/src/test/java/com/multi/mariage/common/fixture/ProductFixture.java
backend/src/test/java/com/multi/mariage/common/fixture/ReviewFixture.java
backend/src/test/java/com/multi/mariage/common/fixture/WeatherFixture.java
backend/src/test/java/com/multi/mariage/hashtag/domain/HashtagRepositoryTest.java
backend/src/test/java/com/multi/mariage/hashtag/service/HashtagServiceTest.java
backend/src/test/java/com/multi/mariage/member/service/MemberServiceTest.java
backend/src/test/java/com/multi/mariage/product/service/ProductModifyServiceTest.java
backend/src/test/java/com/multi/mariage/review/controller/ReviewModifyControllerTest.java
backend/src/test/java/com/multi/mariage/review/domain/ReviewRepositoryTest.java
backend/src/test/java/com/multi/mariage/review/service/ReviewModifyServiceTest.java
backend/src/test/java/com/multi/mariage/review_hashtag/domain/ReviewHashtagRepositoryTest.java
backend/src/test/java/com/multi/mariage/review_hashtag/service/ReviewHashtagServiceTest.java
backend/src/test/java/com/multi/mariage/storage/service/StorageServiceTest.java

[BE] 리뷰 작성에 대한 테스트 코드를 작성

---

frontend/src/components/Detail/Pairing/Pairing.styled.ts
frontend/src/components/Detail/Pairing/Pairing.tsx
frontend/src/components/Detail/ProductContent/ProductContent.styled.ts
frontend/src/components/Detail/Review/RateStatistic/RateStatistic.styled.ts
frontend/src/components/Detail/Review/ReviewCategory/ReviewCategory.styled.ts
frontend/src/components/Detail/Review/ReviewContent/ReviewContent.styled.ts
frontend/src/components/Detail/Review/ReviewEdit/FoodContent/FoodCategory.styled.ts
frontend/src/components/Detail/Review/ReviewEdit/FoodContent/FoodImg.styled.ts
frontend/src/components/Detail/Review/ReviewEdit/HashTag/HashTag.styled.ts
frontend/src/components/Detail/Review/ReviewEdit/ReviewEdit.styled.ts
frontend/src/components/Detail/Review/ReviewEditModal/ReviewEditModal.styled.ts
frontend/src/components/Footer/Footer.styled.ts
frontend/src/components/Header/Dropdown/Dropdown.styled.ts
frontend/src/components/Header/Search/Search.styled.ts
frontend/src/components/Loading/Loading.styled.ts
frontend/src/components/Loading/Loading.tsx
frontend/src/components/Main/SearchFilter/SearchFilter.styled.ts
frontend/src/styles/global.tsx

#198 
글로벌 css 수정 (기본 설정 추가)
글로벌 css 수정에 따라 main,detail,header,footer css 코드 정리
제품상세페이지 리뷰 프로필 미디어쿼리 수정
메인페이지 검색필터 멀티레인지 여백 수정

[FE] 글로벌 css 수정 및 전체컴포넌트 css 코드 정리

---

frontend/src/components/Header/Dropdown/Dropdown.tsx
frontend/src/components/Header/User/Profile.tsx
frontend/src/components/Product/Filter/Filter.styled.ts
frontend/src/components/Product/Filter/Filter.tsx
frontend/src/pages/Product/Product.tsx

[FE] 상위 카테고리를 선택한 상태에서 하위 카테고리 선택이 안되는 버그 수정

---

backend/src/main/java/com/multi/mariage/member/domain/Member.java
backend/src/main/java/com/multi/mariage/product/domain/Product.java
backend/src/main/java/com/multi/mariage/review/domain/Review.java

[BE] 이미지와 연관 관계를 가지고 있는 부모에게 cascade를 설정

---

backend/src/main/java/com/multi/mariage/global/data/Fixture/MemberFixture.java
backend/src/main/java/com/multi/mariage/global/data/Fixture/ReviewFixture.java
backend/src/main/java/com/multi/mariage/global/data/LoaderData.java
backend/src/main/java/com/multi/mariage/review/domain/Review.java

[BE] 더미데이터 파일 구조 변경

---

backend/src/docs/asciidoc/Auth.adoc
backend/src/docs/asciidoc/Category.adoc
backend/src/docs/asciidoc/Member.adoc
backend/src/docs/asciidoc/Product.adoc
backend/src/docs/asciidoc/Review.adoc
backend/src/docs/asciidoc/Storage.adoc
backend/src/main/java/com/multi/mariage/global/data/Fixture/ReviewFixture.java
backend/src/main/java/com/multi/mariage/global/data/LoaderData.java
backend/src/main/java/com/multi/mariage/hashtag/service/HashtagService.java
backend/src/main/java/com/multi/mariage/product/controller/ProductFindController.java
backend/src/main/java/com/multi/mariage/product/domain/query/ProductRepositoryCustom.java
backend/src/main/java/com/multi/mariage/product/domain/query/ProductRepositoryImpl.java
backend/src/main/java/com/multi/mariage/product/dto/response/ProductMainCardResponse.java
backend/src/main/java/com/multi/mariage/product/service/ProductFindService.java
backend/src/main/resources/application-logging.yml
backend/src/test/java/com/multi/mariage/common/annotation/ControllerTest.java
backend/src/test/java/com/multi/mariage/common/fixture/ReviewFixture.java
backend/src/test/java/com/multi/mariage/product/controller/ProductFindControllerTest.java
backend/src/test/java/com/multi/mariage/product/domain/ProductRepositoryQueryTest.java
backend/src/test/java/com/multi/mariage/product/service/ProductFindServiceTest.java

[BE] 전체 기간  제품 추천 기능 구현

---

frontend/src/components/Product/Filter/Filter.tsx

[FE] 누락된 코드 수정

---

backend/src/main/java/com/multi/mariage/global/data/LoaderData.java
backend/src/main/java/com/multi/mariage/like/controller/LikeController.java
backend/src/main/java/com/multi/mariage/like/domain/Like.java
backend/src/main/java/com/multi/mariage/like/domain/LikeRepository.java
backend/src/main/java/com/multi/mariage/like/dto/request/LikeSaveRequest.java
backend/src/main/java/com/multi/mariage/like/exception/LikeErrorCode.java
backend/src/main/java/com/multi/mariage/like/exception/LikeException.java
backend/src/main/java/com/multi/mariage/like/service/LikeService.java
backend/src/main/java/com/multi/mariage/review/exception/ReviewErrorCode.java
backend/src/main/java/com/multi/mariage/review/exception/ReviewException.java
backend/src/main/java/com/multi/mariage/review/service/ReviewFindService.java
backend/src/test/java/com/multi/mariage/common/annotation/ControllerTest.java
backend/src/test/java/com/multi/mariage/common/annotation/RepositoryTest.java
backend/src/test/java/com/multi/mariage/common/annotation/ServiceTest.java
backend/src/test/java/com/multi/mariage/common/fixture/ReviewFixture.java
backend/src/test/java/com/multi/mariage/like/controller/LikeControllerTest.java
backend/src/test/java/com/multi/mariage/like/domain/LikeRepositoryTest.java
backend/src/test/java/com/multi/mariage/like/service/LikeServiceTest.java

[BE] 좋아요 등록 기능 구현

---

backend/src/main/java/com/multi/mariage/global/data/LoaderData.java
frontend/src/apis/request/member.ts
frontend/src/components/MyInformation/Password/Password.styled.ts
frontend/src/components/MyInformation/Password/Password.tsx
frontend/src/components/MyInformation/Profile/Profile.styled.ts
frontend/src/components/MyInformation/Profile/Profile.tsx
frontend/src/constants/path.ts
frontend/src/pages/MyInformation/MyInformation.styled.ts
frontend/src/pages/MyInformation/MyInformation.tsx

#124 
nav 메뉴 위치 수정
프로필수정 컴포넌트
- 전체 UI 수정 (미디어쿼리)
비밀번호변경 컴포넌트
- 전체 UI 수정
- 비밀번호 업데이트 기능 추가 (axios로 변경된 데이터 전송)

[FE] 마이페이지 UI 수정 및 기능 추가

---

backend/src/docs/asciidoc/Product.adoc
backend/src/main/java/com/multi/mariage/product/controller/ProductFindController.java
backend/src/main/java/com/multi/mariage/product/domain/query/ProductRepositoryCustom.java
backend/src/main/java/com/multi/mariage/product/domain/query/ProductRepositoryImpl.java
backend/src/main/java/com/multi/mariage/product/service/ProductFindService.java
backend/src/test/java/com/multi/mariage/common/annotation/ServiceTest.java
backend/src/test/java/com/multi/mariage/common/fixture/WeatherFixture.java
backend/src/test/java/com/multi/mariage/product/controller/ProductFindControllerTest.java
backend/src/test/java/com/multi/mariage/product/domain/ProductRepositoryQueryTest.java
backend/src/test/java/com/multi/mariage/product/service/ProductFindServiceTest.java
backend/src/test/java/com/multi/mariage/review/domain/ReviewRepositoryTest.java
backend/src/test/java/com/multi/mariage/review_hashtag/domain/ReviewHashtagRepositoryTest.java

[BE] 특정 기간사이에 가장 많은 리뷰가 있는 제품을 추천

---

frontend/src/components/Detail/Review/Review.tsx
frontend/src/components/Detail/Review/ReviewEdit/ReviewEdit.tsx

[FE] 리뷰 폼 취소 버튼 기능 수정

---

frontend/src/components/Animation/index.ts

[FIX] 오탈자 수정

---

frontend/src/components/Footer/Footer.styled.ts
frontend/src/components/Header/Dropdown/Dropdown.styled.ts
frontend/src/components/Header/Header.styled.ts
frontend/src/components/Header/Header.tsx
frontend/src/components/Header/Search/Search.styled.ts
frontend/src/components/Header/Search/Search.tsx
frontend/src/components/Header/User/Profile.styled.ts
frontend/src/components/Header/User/Profile.tsx
frontend/src/components/Main/SearchFilter/SearchFilter.tsx
frontend/src/components/Slider/RangeMultiSlider_M/RangeMultiSlider_M_Star.tsx
frontend/src/pages/Review/Review.styled.ts

#218 
메인페이지
- 멀티레인지 별점 기준 값 수정 (1 - 5)
Footer, Header UI 수정
- 미디어쿼리, 기타 UI 수정

[FE] 메인페이지 멀티레인지 수정 / Footer, Header UI 수정

---

.github/workflows/frontend-main.yml
.github/workflows/frontend-pr.yml
.github/workflows/frontend.yml

[Infra] Github Action의 결과를 전송하는 기능 구현

---

.github/workflows/frontend-main.yml
.github/workflows/frontend-pr.yml

#235 
에서 오탈자로 인하여 테스트가 정상적으로 실행 되지 않았습니다.
해당 내용을 수정합니다.

[FIX] Github action 수정

---

.github/workflows/backend-main.yml
.github/workflows/backend-pr.yml
.github/workflows/frontend-main.yml
.github/workflows/frontend-pr.yml
backend/src/test/java/com/multi/mariage/review/service/ReviewModifyServiceTest.java

백엔드의 코드를 CI하는 github action 을 만듭니다.

[BE] 백엔드 Github Action 구현

---

.github/workflows/mariage-pr.yml
.github/workflows/mariage.yml
backend/src/test/java/com/multi/mariage/review/service/ReviewModifyServiceTest.java

테스트 결과중 커밋 메시지를 출력하는 기능을 구현합니다.

[Infra] 커밋 메시지출력 기능 

---

frontend/package-lock.json
frontend/package.json
frontend/public/mockServiceWorker.js
frontend/src/components/Detail/ProductContent/ProductContent.styled.ts
frontend/src/components/Detail/Review/Review.tsx
frontend/src/components/Header/Header.styled.ts
frontend/src/components/MyInformation/Password/Password.styled.ts
frontend/src/constants/path.ts
frontend/src/index.tsx
frontend/src/mocks/browsers.ts
frontend/src/mocks/data/detailReviewData.ts
frontend/src/mocks/detailReviewHandler.ts

#239 
[X] 제품상세페이지 리뷰 무한스크롤 기능 구현 (카카오엔터프라이즈URL참고)
- 아직 데이터가 넘어오는 상황이 아니라 구현 여부 확인 불가
무한스크롤 관련 API 경로 설정
MSW로 API 모킹 (msw라이브러리 설치, src 내 mocks폴더 및 관련 파일 추가)
Header, 비밀번호변경 컴포넌트 : nth-chile() → nth-of-type() 으로 css 코드 변경
(브라우저 상 경고 및 권장사항)

[FE] 제품상세페이지 리뷰 무한스크롤 기능 구현

---

.github/workflows/mariage-pr.yml
backend/src/main/java/com/multi/mariage/global/data/Fixture/ReviewFixture.java
backend/src/main/java/com/multi/mariage/global/data/LoaderData.java
backend/src/main/java/com/multi/mariage/member/domain/Member.java
backend/src/main/java/com/multi/mariage/review/controller/ReviewFindController.java
backend/src/main/java/com/multi/mariage/review/domain/ReviewRepository.java
backend/src/main/java/com/multi/mariage/review/domain/query/ReviewRepositoryCustom.java
backend/src/main/java/com/multi/mariage/review/domain/query/ReviewRepositoryImpl.java
backend/src/main/java/com/multi/mariage/review/dto/ReviewsPagingCond.java
backend/src/main/java/com/multi/mariage/review/dto/resonse/ProductReviewsResponse.java
backend/src/main/java/com/multi/mariage/review/service/ReviewFindService.java
backend/src/main/java/com/multi/mariage/review/vo/ProductReviewVO.java
backend/src/main/java/com/multi/mariage/review/vo/product/ProductReviewContentVO.java
backend/src/main/java/com/multi/mariage/review/vo/product/ProductReviewFoodVO.java
backend/src/main/java/com/multi/mariage/review/vo/product/ProductReviewLikeVO.java
backend/src/main/java/com/multi/mariage/review/vo/product/ProductReviewMemberVO.java
backend/src/main/java/com/multi/mariage/weather/service/WeatherService.java

[BE] 제품에 대한 리뷰를 제공

---

backend/src/main/java/com/multi/mariage/weather/domain/Value.java
backend/src/main/java/com/multi/mariage/weather/dto/response/WeatherInfoResponse.java
backend/src/main/java/com/multi/mariage/weather/service/WeatherService.java

#254 
```json
{
"weather": "clouds",
"temp": 26.66
}
```

[BE] 날씨 정보 API 수정

---

backend/src/main/java/com/multi/mariage/review/controller/ReviewFindController.java
backend/src/main/java/com/multi/mariage/review/domain/Sort.java
backend/src/main/java/com/multi/mariage/review/domain/query/ReviewRepositoryImpl.java
backend/src/main/java/com/multi/mariage/review/dto/ReviewsPagingCond.java
backend/src/main/java/com/multi/mariage/review/service/ReviewFindService.java

[BE] 제품 상세페이지에서의 정렬 기능을 제공

---

frontend/src/components/Review/ReviewList.styled.ts

[FE] 리뷰페이지 리뷰컴포넌트 높이 수정 (미디어쿼리)

---

backend/src/main/java/com/multi/mariage/hashtag/domain/Hashtag.java
backend/src/main/java/com/multi/mariage/review/controller/ReviewFindController.java
backend/src/main/java/com/multi/mariage/review/domain/Review.java
backend/src/main/java/com/multi/mariage/review/domain/query/ReviewRepositoryImpl.java
backend/src/main/java/com/multi/mariage/review/service/ReviewFindService.java
backend/src/main/java/com/multi/mariage/review/vo/ProductReviewVO.java
backend/src/main/java/com/multi/mariage/review/vo/product/ProductReviewContentVO.java
frontend/src/@types/paging.ts
frontend/src/@types/review.ts
frontend/src/apis/request/review.ts
frontend/src/components/Detail/Review/Review.tsx
frontend/src/components/Detail/Review/ReviewContent/ReviewContent.tsx
frontend/src/components/Header/User/Profile.tsx
frontend/src/constants/rule.ts
frontend/src/routes/Routes.tsx

[FE] 제품페이지의 리뷰 조회 API 연동

---

frontend/src/components/Animation/Weather.tsx
frontend/src/components/Main/Recommend/Weather/Weather.styled.ts
frontend/src/components/Main/Recommend/Weather/Weather.tsx
package-lock.json

[FE] 메인페이지 날씨 정보 데이터 연동

---

frontend/src/components/Animation/Weather.tsx
frontend/src/components/Main/Recommend/Weather/Weather.styled.ts

[FE] 메인페이지 날씨 및 온도 수정

---

backend/src/main/java/com/multi/mariage/product/controller/ProductFindController.java
backend/src/main/java/com/multi/mariage/product/domain/query/ProductRepositoryCustom.java
backend/src/main/java/com/multi/mariage/product/domain/query/ProductRepositoryImpl.java
backend/src/main/java/com/multi/mariage/product/dto/RecommendCond.java
backend/src/main/java/com/multi/mariage/product/dto/response/ProductContentResponse.java
backend/src/main/java/com/multi/mariage/product/service/ProductFindService.java
backend/src/test/java/com/multi/mariage/product/controller/ProductFindControllerTest.java
backend/src/test/java/com/multi/mariage/product/domain/ProductRepositoryQueryTest.java
backend/src/test/java/com/multi/mariage/product/service/ProductFindServiceTest.java

주류 기간 추천 API를 리팩토링하여 함수를 재사용 하였습니다.

[BE] 주류 기간 추천 API 리팩토링

---

backend/src/main/java/com/multi/mariage/category/domain/Food.java
backend/src/main/java/com/multi/mariage/category/domain/FoodRepository.java
backend/src/main/java/com/multi/mariage/category/service/FoodCategoryService.java
backend/src/main/java/com/multi/mariage/product/domain/Product.java
backend/src/main/java/com/multi/mariage/product/vo/filter/ProductFoodFilterVO.java
backend/src/main/java/com/multi/mariage/review/vo/product/ProductReviewFoodVO.java
backend/src/test/java/com/multi/mariage/category/domain/FoodRepositoryTest.java
backend/src/test/java/com/multi/mariage/category/service/FoodCategoryServiceTest.java
backend/src/test/java/com/multi/mariage/common/annotation/RepositoryTest.java
backend/src/test/java/com/multi/mariage/common/fixture/ReviewFixture.java
backend/src/test/java/com/multi/mariage/like/domain/LikeRepositoryTest.java
backend/src/test/java/com/multi/mariage/product/domain/ProductRepositoryQueryTest.java
backend/src/test/java/com/multi/mariage/review/domain/ReviewRepositoryTest.java
backend/src/test/java/com/multi/mariage/review_hashtag/domain/ReviewHashtagRepositoryTest.java

#283 
`findFoodsByProduct()`와 `findByProductId()` 는 동작 방식이 동일하므로 Repository에서만 테스트를 진행하였습니다.

[BE] 카테고리 패키지의 하위 코드의 테스트 코드를 작성

---

backend/src/docs/asciidoc/Auth.adoc
backend/src/docs/asciidoc/Category.adoc
backend/src/docs/asciidoc/Country.adoc
backend/src/docs/asciidoc/Like.adoc
backend/src/docs/asciidoc/Member.adoc
backend/src/docs/asciidoc/Product.adoc
backend/src/docs/asciidoc/Review.adoc
backend/src/test/java/com/multi/mariage/common/annotation/ServiceTest.java
backend/src/test/java/com/multi/mariage/country/controller/CountryControllerTest.java
backend/src/test/java/com/multi/mariage/country/service/CountryServiceTest.java

[BE] `Country` 패키지 코드의 테스트 코드 작성

---

backend/src/docs/asciidoc/Auth.adoc
backend/src/docs/asciidoc/Category.adoc
backend/src/docs/asciidoc/Country.adoc
backend/src/docs/asciidoc/Like.adoc
backend/src/docs/asciidoc/Member.adoc
backend/src/main/java/com/multi/mariage/hashtag/domain/Hashtag.java
backend/src/main/java/com/multi/mariage/hashtag/service/HashtagService.java
backend/src/main/java/com/multi/mariage/like/service/LikeService.java
backend/src/test/java/com/multi/mariage/like/service/LikeServiceTest.java
backend/src/test/java/com/multi/mariage/member/service/MemberFindServiceTest.java
backend/src/test/java/com/multi/mariage/member/service/MemberModifyServiceTest.java
backend/src/test/java/com/multi/mariage/member/service/MemberServiceTest.java

[BE] Member 테스트 코드 정리 및 작성

---

backend/src/main/java/com/multi/mariage/storage/service/StorageService.java
backend/src/test/java/com/multi/mariage/storage/repository/StorageRepositoryTest.java
backend/src/test/java/com/multi/mariage/storage/service/StorageServiceTest.java
backend/src/test/java/com/multi/mariage/weather/domain/WeatherRepositoryTest.java

#294 
- Weather
- Controller
-  Service
- Repository
- Storage
- Service
- Repository

[BE] Weather, Storage 테스트 코드 작성

---

backend/src/docs/asciidoc/Auth.adoc
backend/src/docs/asciidoc/Category.adoc
backend/src/docs/asciidoc/Country.adoc
backend/src/docs/asciidoc/Like.adoc
backend/src/docs/asciidoc/Member.adoc
backend/src/docs/asciidoc/Product.adoc
backend/src/docs/asciidoc/Review.adoc
backend/src/docs/asciidoc/Weather.adoc
backend/src/main/java/com/multi/mariage/review/domain/Review.java
backend/src/main/java/com/multi/mariage/review/domain/query/ReviewRepositoryCustom.java
backend/src/main/java/com/multi/mariage/review/service/ReviewFindService.java
backend/src/main/java/com/multi/mariage/review/vo/ProductReviewVO.java
backend/src/main/java/com/multi/mariage/weather/controller/WeatherController.java
backend/src/test/java/com/multi/mariage/common/annotation/ServiceTest.java
backend/src/test/java/com/multi/mariage/product/domain/query/ProductRepositoryQueryTest.java
backend/src/test/java/com/multi/mariage/review/controller/ReviewFindControllerTest.java
backend/src/test/java/com/multi/mariage/review/domain/ReviewHashtagRepositoryTest.java
backend/src/test/java/com/multi/mariage/review/domain/query/ReviewRepositoryQueryTest.java
backend/src/test/java/com/multi/mariage/review/service/ReviewFindServiceTest.java
backend/src/test/java/com/multi/mariage/review/service/ReviewHashtagServiceTest.java
backend/src/test/java/com/multi/mariage/weather/controller/WeatherControllerTest.java
backend/src/test/java/com/multi/mariage/weather/service/WeatherServiceTest.java

#297 
- Controller
- Modify
- Find
- Service
- Modify
- Find
- Repository

[BE] Review 테스트 코드를 작성

---

frontend/src/hooks/useAuth.ts
frontend/src/pages/SignUp/SignUp.tsx
frontend/src/routes/PrivateWrapper.tsx
frontend/src/routes/Routes.tsx
frontend/src/utils/auth.ts
frontend/src/utils/boolean.ts

[FE] 라우팅 상세 설정

---

frontend/src/@types/review.ts
frontend/src/components/Detail/Review/ReviewContent/ReviewContent.tsx
frontend/src/components/Main/Recommend/ProductCard/ProductCard.styled.ts
frontend/src/components/Main/Recommend/ProductCard/ProductCard.tsx
frontend/src/components/Main/SearchFilter/SearchFilter.tsx
frontend/src/components/Product/Filter/Filter.styled.ts
frontend/src/components/Product/Filter/Filter.tsx
frontend/src/components/Product/Option/Option.tsx
frontend/src/constants/option.ts
frontend/src/pages/Product/Product.tsx

#305 
- 메인페이지 검색 필터 구현
- 상품페이지 검색 필터 구현

[FE] 검색 필터 기능을 구현

---

backend/src/main/java/com/multi/mariage/category/domain/query/FoodRepositoryImpl.java
backend/src/main/java/com/multi/mariage/product/domain/query/ProductRepositoryImpl.java
frontend/src/components/Main/Recommend/ProductCardCarousel/ProductCardCarousel.styled.ts
frontend/src/components/Main/Recommend/ProductCardCarousel/ProductCardCarousel.tsx
frontend/src/components/Product/ProductCard/ProductCard.tsx
frontend/src/pages/Detail/Detail.tsx

[BUG] 추천 제품이 존재하지 않을 시 추천 기능이 먹통이 되는 버그 수정, 카운터쿼리 버그 수정

---

frontend/src/components/Header/User/Profile.tsx
frontend/src/components/Main/Recommend/ProductCardCarousel/ProductCardCarousel.tsx

[BUG] 새로고침시 헤더의 정보가 사라지는 현상 수정

---

backend/src/main/java/com/multi/mariage/global/data/LoaderData.java
frontend/src/@types/product.ts
frontend/src/@types/select.ts
frontend/src/apis/request/product.ts
frontend/src/assets/Food/FoodImg.tsx
frontend/src/components/Detail/Pairing/Pairing.tsx
frontend/src/components/Detail/ProductContent/ProductContent.tsx
frontend/src/components/Detail/Review/RateStatistic/RateStatistic.tsx
frontend/src/components/Detail/Review/Review.tsx
frontend/src/components/Detail/Review/ReviewEdit/ReviewEdit.tsx
frontend/src/constants/path.ts
frontend/src/pages/Detail/Detail.tsx

#275 
Cannot read properties of undefined (reading 'countryId') 
TypeError: Cannot read properties of undefined (reading 'countryId')
오류발생

[FE] 상품상세페이지 오류

---

backend/src/main/java/com/multi/mariage/global/data/LoaderData.java
backend/src/main/java/com/multi/mariage/product/service/ProductFindService.java

#329 별점 통계 데이터 형식 수정
```
"percentageList": [
{
"reviewRate": 5,
"percentage": 14
},
{
"reviewRate": 4,
"percentage": 14
},
{
"reviewRate": 3,
"percentage": 43
},
{
"reviewRate": 2,
"percentage": 0
},
{
"reviewRate": 1,
"percentage": 29
}
]
```

[BE] 별점 통계 데이터 형식 수정

---

backend/src/main/java/com/multi/mariage/global/data/Fixture/MemberFixture.java
frontend/src/components/Product/Filter/Filter.styled.ts
frontend/src/components/Product/Filter/Filter.tsx
frontend/src/components/Product/Option/Option.styled.ts
frontend/src/components/Product/ProductCard/ProductCard.styled.ts
frontend/src/components/Product/ProductCard/ProductCard.tsx
frontend/src/components/Slider/RangeMultiSlider_F/RangeMultiSlider_F.styled.ts
frontend/src/pages/Product/Product.styled.ts

[FE] 제품페이지 전체 UI(css) 수정

---

frontend/src/components/Main/Recommend/Weather/Weather.styled.ts
frontend/src/components/Main/Recommend/Weather/Weather.tsx

[Bug] 날씨 정보 CSS 수정

---

backend/src/main/java/com/multi/mariage/product/domain/Product.java
backend/src/main/java/com/multi/mariage/product/domain/query/ProductRepositoryCustom.java
backend/src/main/java/com/multi/mariage/product/domain/query/ProductRepositoryImpl.java
backend/src/main/java/com/multi/mariage/product/service/ProductFindService.java
backend/src/main/java/com/multi/mariage/review/dto/response/PageResponse.java
backend/src/test/java/com/multi/mariage/product/domain/query/ProductRepositoryQueryTest.java
frontend/src/constants/rule.ts
frontend/src/mocks/browsers.ts
frontend/src/mocks/detailReviewHandler.ts

[BUG] 필터 검색 옵션이 정상적으로 동작하지 않는 현상 발생 해결

---

frontend/src/components/Detail/Review/Review.tsx
frontend/src/components/Detail/Review/ReviewEdit/ReviewEdit.styled.ts
frontend/src/components/Detail/Review/ReviewEdit/ReviewEdit.tsx
frontend/src/components/Main/Recommend/ProductCard/ProductCard.styled.ts
frontend/src/components/StarRate/Average/SvgStarRateAverage.styled.ts

[BUG] 옵션이 풀리는 CSS 버그 수정

---

backend/src/main/java/com/multi/mariage/category/dto/request/StorageRemoveRequest.java
backend/src/main/java/com/multi/mariage/product/controller/ProductModifyController.java
backend/src/main/java/com/multi/mariage/product/dto/response/ProductModifyResponse.java
backend/src/main/java/com/multi/mariage/review/domain/Review.java
backend/src/main/java/com/multi/mariage/review/service/ReviewFindService.java
backend/src/main/java/com/multi/mariage/review/service/ReviewModifyService.java
backend/src/main/java/com/multi/mariage/review/vo/product/ProductReviewFoodVO.java
backend/src/main/java/com/multi/mariage/storage/controller/StorageController.java
backend/src/main/java/com/multi/mariage/storage/service/StorageService.java
frontend/src/@types/category.ts
frontend/src/@types/review.ts
frontend/src/apis/request/category.ts
frontend/src/apis/request/review.ts
frontend/src/apis/request/storage.ts
frontend/src/components/Detail/Review/Review.tsx
frontend/src/components/Detail/Review/ReviewCategory/ReviewCategory.tsx
frontend/src/components/Detail/Review/ReviewContent/ReviewContent.tsx
frontend/src/components/Detail/Review/ReviewEdit/FoodContent/FoodCategory.tsx
frontend/src/components/Detail/Review/ReviewEdit/FoodContent/FoodImg.tsx
frontend/src/components/Detail/Review/ReviewEdit/HashTag/HashTag.tsx
frontend/src/components/Detail/Review/ReviewEdit/ReviewEdit.tsx
frontend/src/components/Main/Recommend/ProductCard/ProductCard.styled.ts
frontend/src/components/StarRate/Common/StarRate.tsx
frontend/src/constants/key.ts
frontend/src/constants/path.ts
frontend/src/hooks/useFoodCategory.ts
frontend/src/pages/Admin/Admin.tsx
frontend/src/store/status.ts
frontend/src/utils/auth.ts
frontend/src/utils/image.ts

[FE] 리뷰 등록기능을 구현

---

backend/src/main/java/com/multi/mariage/global/data/Fixture/ProductFixture.java
frontend/src/constants/rule.ts

[FIX] 사진 이름 수정

---

frontend/src/components/Product/Filter/Filter.styled.ts
frontend/src/components/Product/Filter/Filter.tsx
frontend/src/components/Slider/RangeMultiSlider_F/RangeMultiSlider_F.styled.ts
frontend/src/constants/option.ts
frontend/src/pages/Product/Product.styled.ts
frontend/src/pages/Product/Product.tsx

[FE] 사용자가 어떠한 필터를 적용했는지 알려주는 UI를 구현

---

frontend/src/components/Product/Option/Option.styled.ts
frontend/src/components/Product/Option/Option.tsx
frontend/src/components/Product/ProductCard/ProductCard.styled.ts
frontend/src/pages/Product/Product.tsx

[Bug] 상품페이지 정렬 버튼 수정

---

backend/src/main/java/com/multi/mariage/product/domain/query/ProductRepositoryImpl.java
backend/src/main/java/com/multi/mariage/product/dto/request/ProductFindByFilterRequest.java
frontend/src/apis/request/product.ts
frontend/src/components/Header/Dropdown/Dropdown.tsx
frontend/src/components/Main/SearchFilter/SearchFilter.tsx
frontend/src/components/Product/Filter/Filter.tsx
frontend/src/components/Product/Option/Option.tsx
frontend/src/hooks/useIntersectionObserver.ts
frontend/src/pages/Product/Product.styled.ts
frontend/src/pages/Product/Product.tsx

[BUG] 제품페이지 데이터 조회 버그 수정

---

backend/src/main/java/com/multi/mariage/product/domain/query/ProductRepositoryImpl.java
backend/src/main/java/com/multi/mariage/review/domain/Sort.java
backend/src/main/java/com/multi/mariage/review/domain/query/ReviewRepositoryImpl.java
backend/src/main/resources/application.yml
backend/src/test/java/com/multi/mariage/review/domain/query/ReviewRepositoryQueryTest.java
frontend/src/@types/select.ts
frontend/src/components/Detail/Review/Review.styled.ts
frontend/src/components/Detail/Review/Review.tsx
frontend/src/components/Detail/Review/ReviewCategory/ReviewCategory.tsx
frontend/src/components/Header/Search/Search.tsx
frontend/src/components/Product/Filter/Filter.styled.ts
frontend/src/components/Product/Filter/Filter.tsx
frontend/src/constants/option.ts
frontend/src/pages/Product/Product.tsx

[FE] 제품 페이지의 리뷰 무한 스크롤을 구현

---

backend/src/main/java/com/multi/mariage/product/domain/Product.java
backend/src/main/java/com/multi/mariage/product/domain/query/ProductRepositoryImpl.java
backend/src/main/java/com/multi/mariage/product/service/ProductFindService.java
backend/src/main/java/com/multi/mariage/product/vo/filter/ProductReviewFilterVO.java

[BUG] 제품페이지 무한스크롤 버그 수정

---

backend/src/main/java/com/multi/mariage/global/config/WebConfig.java
backend/src/main/java/com/multi/mariage/global/data/LoaderData.java
frontend/src/components/Detail/Review/RateStatistic/RateStatistic.styled.ts
frontend/src/components/Detail/Review/RateStatistic/RateStatistic.tsx
frontend/src/components/Detail/Review/ReviewCategory/ReviewCategory.styled.ts
frontend/src/components/Detail/Review/ReviewCategory/ReviewCategory.tsx
frontend/src/components/Detail/Review/ReviewContent/ReviewContent.styled.ts
frontend/src/components/Detail/Review/ReviewEdit/ReviewEdit.styled.ts
frontend/src/components/Main/Recommend/ProductCard/ProductCard.tsx
frontend/src/components/Modal/ReviewImage/ReviewImage.styled.ts
frontend/src/components/Modal/ReviewImage/ReviewImage.tsx

#364 
제품상세페이지
- 리뷰 이미지 크기 수정
- 리뷰 이미지 모달 이미지 크기 수정
메인페이지
- 상품 캐러셀 상품명 8자 이상 시 마스킹 처리

[FE] 제품상세페이지 / 메인페이지 수정

---

frontend/src/components/Detail/Review/RateStatistic/RateStatistic.styled.ts
frontend/src/components/Detail/Review/RateStatistic/RateStatistic.tsx
frontend/src/pages/Product/Product.tsx

[FE] 제품페이지로 이동시 보여주는 화면 기능 구현

---

frontend/src/apis/request/member.ts
frontend/src/components/MyInformation/Profile/Profile.styled.ts
frontend/src/components/MyInformation/Profile/Profile.tsx
frontend/src/constants/path.ts

#385 
마이페이지 사진변경/삭제 기능 구현
적용 버튼 생성 및 기능 구현
Api 연동

[FE] 마이페이지 사진변경/삭제 기능 구현

---

backend/src/main/java/com/multi/mariage/member/controller/MemberModifyController.java
backend/src/main/java/com/multi/mariage/member/domain/Member.java
backend/src/main/java/com/multi/mariage/report/Controller/ReportController.java
backend/src/main/java/com/multi/mariage/report/domain/Report.java
backend/src/main/java/com/multi/mariage/report/domain/ReportRepository.java
backend/src/main/java/com/multi/mariage/report/domain/query/ReportRepositoryCustom.java
backend/src/main/java/com/multi/mariage/report/domain/query/ReportRepositoryImpl.java
backend/src/main/java/com/multi/mariage/report/dto/response/ReportResponse.java
backend/src/main/java/com/multi/mariage/report/exception/ReportErrorCode.java
backend/src/main/java/com/multi/mariage/report/exception/ReportException.java
backend/src/main/java/com/multi/mariage/report/service/ReportService.java
backend/src/main/java/com/multi/mariage/review/domain/Review.java
backend/src/main/java/com/multi/mariage/review/domain/query/ReviewRepositoryImpl.java
frontend/src/@types/review.ts
frontend/src/apis/request/review.ts
frontend/src/components/Detail/Review/ReviewContent/ReviewContent.tsx
frontend/src/constants/path.ts

[BE] 신고 기능 구현

---

frontend/src/@types/review.ts
frontend/src/apis/request/member.ts
frontend/src/components/Header/User/Profile.tsx
frontend/src/pages/Review/Review.styled.ts
frontend/src/pages/Review/Review.tsx

#377 
리뷰페이지
- 프로필 api연동
- 프로필 이미지 원형으로 css 변경

[FE] 리뷰페이지 프로필 api연동

---

backend/src/main/java/com/multi/mariage/review/controller/ReviewFindController.java
backend/src/main/java/com/multi/mariage/review/domain/query/ReviewRepositoryImpl.java
backend/src/main/java/com/multi/mariage/review/dto/cond/MemberReviewsPagingCond.java
backend/src/main/java/com/multi/mariage/review/dto/request/ReviewFindRequest.java
backend/src/main/java/com/multi/mariage/review/service/ReviewFindService.java
backend/src/test/java/com/multi/mariage/review/controller/ReviewFindControllerTest.java
backend/src/test/java/com/multi/mariage/review/domain/query/ReviewRepositoryQueryTest.java
backend/src/test/java/com/multi/mariage/review/service/ReviewFindServiceTest.java

[BE] 리뷰 페이지의 유저 정보를 가져오는 API를 수정

---

backend/src/main/java/com/multi/mariage/global/data/LoaderData.java
frontend/src/components/Header/User/Profile.tsx
frontend/src/components/MyInformation/Profile/Profile.styled.ts
frontend/src/pages/Review/Review.styled.ts
frontend/src/pages/Review/Review.tsx

[FE] 헤더 닉네임 마스킹 수정

---

backend/src/main/java/com/multi/mariage/MariageApplication.java
backend/src/main/java/com/multi/mariage/product/controller/ProductFindController.java
backend/src/main/java/com/multi/mariage/product/domain/query/ProductRepositoryCustom.java
backend/src/main/java/com/multi/mariage/product/domain/query/ProductRepositoryImpl.java
backend/src/main/java/com/multi/mariage/product/dto/response/ProductSearchResponse.java
backend/src/main/java/com/multi/mariage/product/service/ProductFindService.java
frontend/src/@types/product.ts
frontend/src/apis/request/product.ts
frontend/src/components/Header/Search/Search.styled.ts
frontend/src/components/Header/Search/Search.tsx
frontend/src/constants/path.ts

[BE, FE] 검색 자동완성 기능 구현

---

backend/src/main/java/com/multi/mariage/global/data/LoaderData.java
backend/src/main/java/com/multi/mariage/product/controller/ProductFindController.java
backend/src/main/java/com/multi/mariage/product/domain/query/ProductRepositoryCustom.java
backend/src/main/java/com/multi/mariage/product/domain/query/ProductRepositoryImpl.java
backend/src/main/java/com/multi/mariage/product/service/ProductFindService.java
backend/src/main/java/com/multi/mariage/review/domain/query/ReviewRepositoryCustom.java
backend/src/main/java/com/multi/mariage/review/domain/query/ReviewRepositoryImpl.java
backend/src/main/java/com/multi/mariage/review/service/ReviewModifyService.java
backend/src/main/java/com/multi/mariage/slope/domain/member/MemberSlope.java
backend/src/main/java/com/multi/mariage/slope/domain/member/MemberSlopeRepository.java
backend/src/main/java/com/multi/mariage/slope/domain/member/query/MemberSlopeRepositoryCustom.java
backend/src/main/java/com/multi/mariage/slope/domain/member/query/MemberSlopeRepositoryImpl.java
backend/src/main/java/com/multi/mariage/slope/domain/product/ProductSlope.java
backend/src/main/java/com/multi/mariage/slope/domain/product/ProductSlopeRepository.java
backend/src/main/java/com/multi/mariage/slope/domain/product/query/ProductSlopeRepositoryCustom.java
backend/src/main/java/com/multi/mariage/slope/domain/product/query/ProductSlopeRepositoryImpl.java
backend/src/main/java/com/multi/mariage/slope/service/SlopeService.java
backend/src/main/resources/application.yml
frontend/src/apis/request/product.ts
frontend/src/components/Header/User/Profile.tsx
frontend/src/components/Main/Recommend/ProductCard/ProductCard.tsx
frontend/src/components/Main/Recommend/ProductCardCarousel/ProductCardCarousel.tsx
frontend/src/constants/path.ts

[BE] 슬로프 원 추천기 구현

---

frontend/src/components/Detail/Review/ReviewContent/ReviewContent.styled.ts
frontend/src/components/Detail/Review/ReviewContent/ReviewContent.tsx
frontend/src/components/Header/Search/Search.styled.ts
frontend/src/components/Header/Search/Search.tsx

[FE] search ui 구현

---

frontend/src/@types/product.ts
frontend/src/@types/review.ts
frontend/src/apis/request/review.ts
frontend/src/components/Button/Like/Like.tsx
frontend/src/components/Detail/Review/ReviewContent/ReviewContent.styled.ts
frontend/src/components/Detail/Review/ReviewContent/ReviewContent.tsx
frontend/src/components/Review/ReviewList.styled.ts
frontend/src/components/Review/ReviewList.tsx
frontend/src/components/SnackBar/SnackBar.styled.ts
frontend/src/components/SnackBar/SnackBar.tsx
frontend/src/constants/option.ts
frontend/src/constants/path.ts
frontend/src/pages/Detail/Detail.tsx
frontend/src/pages/Review/Review.styled.ts
frontend/src/pages/Review/Review.tsx

[FE] 리뷰페이지 API 연동

---

frontend/src/components/Review/ReviewList.styled.ts
frontend/src/components/Review/ReviewList.tsx
frontend/src/pages/Review/Review.styled.ts
frontend/src/pages/Review/Review.tsx

[FE] 리뷰 페이지 수정

---

backend/src/main/java/com/multi/mariage/category/domain/FoodCategory.java
backend/src/main/java/com/multi/mariage/review/controller/ReviewFindController.java
backend/src/main/java/com/multi/mariage/review/controller/ReviewModifyController.java
backend/src/main/java/com/multi/mariage/review/domain/Review.java
backend/src/main/java/com/multi/mariage/review/domain/ReviewRepository.java
backend/src/main/java/com/multi/mariage/review/domain/query/ReviewRepositoryCustom.java
backend/src/main/java/com/multi/mariage/review/domain/query/ReviewRepositoryImpl.java
backend/src/main/java/com/multi/mariage/review/dto/request/ReviewUpdateRequest.java
backend/src/main/java/com/multi/mariage/review/dto/response/ReviewUpdateInfoResponse.java
backend/src/main/java/com/multi/mariage/review/dto/response/ReviewUpdateResponse.java
backend/src/main/java/com/multi/mariage/review/service/ReviewFindService.java
backend/src/main/java/com/multi/mariage/review/service/ReviewModifyService.java
backend/src/test/java/com/multi/mariage/common/fixture/ReviewFixture.java
backend/src/test/java/com/multi/mariage/review/controller/ReviewModifyControllerTest.java
backend/src/test/java/com/multi/mariage/review/service/ReviewModifyServiceTest.java
frontend/src/@types/review.ts
frontend/src/apis/request/review.ts
frontend/src/assets/CountryFlag/CountryFlag.tsx
frontend/src/components/Detail/Review/ReviewContent/ReviewContent.tsx
frontend/src/components/Detail/Review/ReviewContent/ReviewUpdate/ReviewUpdate.tsx
frontend/src/components/Review/ReviewList.styled.ts
frontend/src/components/Review/ReviewList.tsx
frontend/src/constants/path.ts
frontend/src/hooks/useImage.ts

[BE, FE] 리뷰 수정기능 구현

---

backend/src/main/java/com/multi/mariage/global/data/LoaderData.java
frontend/src/components/Button/Like/Like.styled.ts
frontend/src/components/Detail/Review/ReviewContent/ReviewContent.styled.ts
frontend/src/components/Main/Recommend/ProductCard/ProductCard.styled.ts
frontend/src/components/Main/Recommend/ProductCard/ProductCard.tsx
frontend/src/components/Main/Recommend/ProductCardCarousel/ProductCardCarousel.tsx
frontend/src/components/Product/Filter/Filter.styled.ts
frontend/src/pages/MyInformation/MyInformation.styled.ts
frontend/src/pages/Review/Review.styled.ts
frontend/src/pages/Review/Review.tsx

#409 
메인페이지 캐러샐 추천옵션 시 문구 추가
리뷰페이지 상단 내비 css효과 추가
제품페이지 필터 여백 조정 (미디어쿼리)
제품상세페이지 리뷰 부분 css 수정

[FE] 전체페이지 css 수정
